# Gundam Example LRG

Example code to estimate a 2D projected correlation function using a sample of SDSS Luminous Red Galaxies.

In [8]:
import gundam as gun
from astropy.table import Table


# DEFINE PARAMETERS  ==========================================================
par = gun.packpars(kind="acf")
par.doboot = False  # Do bootstrap error estimates
par.dsept = 0.10
par.nsept = 33
par.septmin = 0.01
par.grid = 1
par.estimator = "NAT"  # Choose Landy-Szalay estimator for the PCF
par.description = "example01"  # Description label
par.autogrid = False

# READ DATA FILES  ============================================================
gals = Table.read("../../tests/data/DATA.fits")
gals = gals[["ra", "dec"]]
gals["wei"] = 1.0

rans = Table.read("../../tests/data/RAND.fits")
rans = rans[["ra", "dec"]]
rans["wei"] = 1.0

# ==============================================================================
# CALCULATE THE CORRELATION
nt = 1  # Threads to use
cnt = gun.acf(gals, rans, par, nthreads=nt, plot=False, write=False)
# ==============================================================================


Missing outfn: default to run001
START!   06/21/24  13:36:18


Name of output set to : run001
Calling Information  ================================================
table        = 
table_nrows  = 84383
table1       = 
table1_nrows = 227336
nthreads     = 1
write        = False
plot         = False
Sample boundaries : (0.00000, 360.00000, -3.75118, 70.25317)
Sample seems to cross RA=0 : False
Autogrid OFF
SK grid size [dec,ra]       : [20, 20]
SK grid1 size [dec,ra]      : [20, 20]
Pixsort time (s)            : 0.078
SK-LL tables build time (s) : 0.754
====  Counting DD pairs in 20 DEC strips  =====
      [for progress updates check run001.fortran.log]
  
Done with DD calculations. Looptime (s) : 13.502
====  Counting DD pairs in  20 DEC strips  ====
   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  
====  Counting RR pairs in 20 DEC strips  =====
      [for progress updates check run001.fortran.log]
Done with RR calculations. Looptime (s) : 128.694
  
====  Counting RR pairs in  20 DEC strips  ====
   1   2   3   4  

In [11]:
print(cnt.par)

Pretty printing has been turned ON


In [27]:
import numpy as np

np.save('../../tests/data/dd_acf.npy', cnt.dd)
np.save('../../tests/data/rr_acf.npy', cnt.rr)
np.save('../../tests/data/w_acf_nat.npy', cnt.wth)

In [30]:
print(np.sum(cnt.dd - np.load('../../tests/data/dd_acf.npy')))
print(np.sum(cnt.rr - np.load('../../tests/data/rr_acf.npy')))
print(np.sum(cnt.wth - np.load('../../tests/data/w_acf_nat.npy')))

0.0
0.0
0.0


In [1]:
import gundam as gun
from astropy.table import Table
import numpy as np
from munch import Munch


# DEFINE PARAMETERS  ==========================================================
par = Munch()
par.dsept = 0.10
par.nsept = 33
par.septmin = 0.01
par.estimator = "NAT"  # Choose Landy-Szalay estimator for the PCF

# READ DATA FILES  ============================================================
gals = Table.read("../../tests/data/DATA.fits")
gals = gals[["ra", "dec"]]

rans = Table.read("../../tests/data/RAND.fits")
rans = rans[["ra", "dec"]]
# ==============================================================================
# CALCULATE THE CORRELATION
dd, rr, wth = gun.acf_naiveway(gals['ra'].data, gals['dec'].data, rans['ra'].data, rans['dec'].data, par)
# ==============================================================================

In [31]:
print(np.sum(dd - cnt.dd))
print(np.sum(rr - cnt.rr))
print(np.sum(wth - cnt.wth))

0.0
0.0
0.0


In [8]:
print(np.sum(dd - np.load('../../tests/data/dd_acf.npy')))
print(np.sum(rr - np.load('../../tests/data/rr_acf.npy')))
print(np.sum(wth - np.load('../../tests/data/w_acf_nat.npy')))

0.0
0.0
0.0


In [3]:
dd

array([9.15000000e+02, 1.33600000e+03, 1.75000000e+03, 2.61900000e+03,
       3.55300000e+03, 4.96900000e+03, 7.02300000e+03, 9.86100000e+03,
       1.38990000e+04, 1.99230000e+04, 2.83680000e+04, 3.96120000e+04,
       5.70030000e+04, 7.99690000e+04, 1.13296000e+05, 1.60199000e+05,
       2.31993000e+05, 3.38254000e+05, 4.99530000e+05, 7.50321000e+05,
       1.13553400e+06, 1.73301300e+06, 2.64083900e+06, 4.02869000e+06,
       6.18941500e+06, 9.46402900e+06, 1.44341790e+07, 2.20575820e+07,
       3.37935260e+07, 5.12908750e+07, 7.66605560e+07, 1.13662244e+08,
       1.66670601e+08])

In [4]:
rr

array([6.23000000e+02, 1.04400000e+03, 1.63000000e+03, 2.60000000e+03,
       4.18200000e+03, 6.48100000e+03, 1.05790000e+04, 1.63410000e+04,
       2.58780000e+04, 4.12280000e+04, 6.56310000e+04, 1.04604000e+05,
       1.63916000e+05, 2.59321000e+05, 4.08985000e+05, 6.50041000e+05,
       1.02906600e+06, 1.62381300e+06, 2.56846300e+06, 4.05438200e+06,
       6.39578000e+06, 1.00895510e+07, 1.58876700e+07, 2.49918200e+07,
       3.92535390e+07, 6.15647820e+07, 9.62923910e+07, 1.50134370e+08,
       2.32991661e+08, 3.59157494e+08, 5.49585169e+08, 8.31881878e+08,
       1.23739900e+09])

In [5]:
wth

array([ 9.66013708e+00,  8.28828861e+00,  6.79256056e+00,  6.31125435e+00,
        5.16653103e+00,  4.56489171e+00,  3.81845484e+00,  3.37997943e+00,
        2.89836580e+00,  2.50745582e+00,  2.13725225e+00,  1.74857898e+00,
        1.52409739e+00,  1.23827642e+00,  1.01065213e+00,  7.88746484e-01,
        6.36294210e-01,  5.11947353e-01,  4.11620653e-01,  3.43235554e-01,
        2.88654123e-01,  2.46693579e-01,  2.06455914e-01,  1.70026527e-01,
        1.44459761e-01,  1.15766861e-01,  8.80024119e-02,  6.63690176e-02,
        5.27442373e-02,  3.65372583e-02,  1.24339556e-02, -8.29088625e-03,
       -2.23599533e-02])